"""Create attack_logs table

Revision ID: 002_create_attack_logs
Revises: 001_create_sessions
Create Date: 2024 migration

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers
revision = '002_create_attack_logs'
down_revision = '001_create_sessions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ip', postgresql.INET(), nullable=False),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('method', sa.String(), nullable=False),
        sa.Column('path', sa.String(), nullable=False),
        sa.Column('query', sa.String(), nullable=True),
        sa.Column('body', sa.JSON(), nullable=True),
        sa.Column('attack_type', sa.String(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('rule_matched', sa.String(), nullable=True),
        sa.Column('fake_response', sa.JSON(), nullable=True),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('asn', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_logs_created_at'), 'attack_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_attack_logs_ip'), 'attack_logs', ['ip'], unique=False)
    op.create_index(op.f('ix_attack_logs_session'), 'attack_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_attack_logs_type'), 'attack_logs', ['attack_type'], unique=False)
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=text('gen_random_uuid()'), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False, default_='admin'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_attack_logs_type'), table_name='attack_logs')
    op.drop_index(op.f('ix_attack_logs_session'), table_name='attack_logs')
    op.drop_index(op.f('ix_attack_logs_ip'), table_name='attack_logs')
    op.drop_index(op.f('ix_attack_logs_created_at'), table_name='attack_logs')
    op.drop_table('attack_logs')
    # ### end Alembic commands ###

